# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Test
      run: |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        echo "COVERAGE=$(go tool cover -func=coverage.txt | grep total | grep -Eo '[0-9]+\.[0-9]+')" >> $GITHUB_ENV

    - name: Update Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 0b88dea0e941cb4e21241d03dcce1ffc
        filename: coverage.json
        label: coverage
        message: ${{ env.COVERAGE }}%
        valColorRange: '0:0:red, 60:60:yellow, 80:80:green'
        maxColorRange: 100
        minColorRange: 0

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.txt
        if-no-files-found: error

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.1

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.84.2
